apps/web/src/components/comments/comment/comment.tsx
=> Breaking long words in the comment section

apps/web/src/components/auth/sign-in-form/sign-in-form.state.ts, apps/web/src/components/auth/sign-in-form/sign-in-form.view.tsx, apps/web/src/components/auth/sign-up-form/sign-up-form.state.ts, apps/web/src/components/auth/sign-up-form/sign-up-form.view.tsx, apps/web/src/components/comments/comment-vote/comment-vote.state.ts, apps/web/src/components/comments/comment-vote/comment-vote.view.tsx, apps/web/src/components/comments/new-comment-form/new-comment-form.state.ts, apps/web/src/components/comments/new-comment-form/new-comment-form.view.tsx, apps/web/src/components/posts/new-post-form/new-post-form.state.ts, apps/web/src/components/posts/new-post-form/new-post-form.view.tsx, apps/web/src/components/posts/post-vote/post-vote.state.ts, apps/web/src/components/posts/post-vote/post-vote.view.tsx, apps/web/src/pages/_app.tsx, apps/web/src/pages/new.tsx, apps/web/src/pages/posts/[id].tsx, apps/web/src/pages/sign-up/[code].tsx, apps/web/src/pages/subsites/[slug].tsx, apps/web/src/pages/subsites/index.tsx, apps/web/src/pages/top/[interval].tsx, apps/web/src/pages/users/[id].tsx, apps/web/src/utilities/initial-data.ts, apps/web/src/utilities/trpc.ts
=> Поправил авторизацию

apps/web/src/components/renderer/renderer.tsx
=> Поправил растягивание картинок в постах

apps/web/src/components/editor/editor.tsx, apps/web/src/components/editor/reddit.tsx, apps/web/src/components/editor/youtube.tsx, apps/web/src/components/embeds/index.ts, apps/web/src/components/embeds/reddit-embed.tsx, apps/web/src/components/embeds/youtube-embed.tsx, apps/web/src/components/renderer/renderer.tsx
=> Добавил встраивание YouTube и Reddit

apps/web/src/components/renderer/renderer.tsx
=> Добавил открытие фула при клике на картинку

apps/web/src/pages/users/[id].tsx
=> fix: user details should not return 404 for guests

apps/web/src/pages/donate.tsx
=> Новая страница «Поддержать»

apps/web/src/components/auth/sign-in-form/sign-in-form.state.ts
=> Исправил чувствительность к регистру при входе

apps/web/src/components/renderer/renderer.tsx, apps/web/src/styles/globals.css
=> Поправил баги с картинками в постах

apps/web/src/pages/posts/[id].tsx
=> Исправил пустой заголовок страницы

apps/api/src/images.ts
=> Добавил поддержку GIF

apps/web/src/components/posts/new-post-form/new-post-form.state.ts, apps/web/src/components/posts/new-post-form/new-post-form.view.tsx
=> Добавил превью новых постов

apps/api/src/modules/comments/inputs/get-comments-by-post.ts, apps/api/src/modules/comments/procedures/get-by-post.ts, apps/api/src/modules/comments/selector.ts, apps/api/src/modules/posts/procedures/get-top.ts, apps/web/package.json, apps/web/src/components/comments/new-comments/new-comments.tsx, apps/web/src/components/comments/post-comments/comment/comment.tsx, apps/web/src/components/comments/post-comments/post-comments.tsx, apps/web/src/components/posts/new-post-form/new-post-form.view.tsx, apps/web/src/hooks/index.ts, apps/web/src/hooks/use-intersection-observer.ts, apps/web/src/pages/posts/[id].tsx, packages/typescript-paths/package.json, pnpm-lock.yaml
=> Добавил загрузку комментария по ссылке со всей веткой

apps/api/src/modules/posts/procedures/get-top.ts
=> fix: hide posts with negative score

apps/web/src/styles/globals.css
=> feat: sticky sidebar

apps/web/src/components/renderer/renderer.tsx
=> Добавил кнопку «Читать дальше»

apps/web/src/components/sidebar/menu.tsx
=> Исправил ссылку на Discord

apps/api/src/modules/comments/inputs/create-comment.input.ts, apps/api/src/modules/posts/inputs/create-post.input.ts, apps/api/src/modules/posts/inputs/update-post.input.ts, apps/api/src/utilities/zod-types.ts, apps/web/src/components/comments/post-comments/new-comment-form/new-comment-form.state.ts, apps/web/src/components/comments/post-comments/new-comment-form/new-comment-form.view.tsx, apps/web/src/components/posts/edit-post-form/edit-post-form.state.ts, apps/web/src/components/posts/edit-post-form/edit-post-form.view.tsx
=> Ограничил длину заголовка поста и комментария

apps/web/next.config.js, apps/web/src/hooks/index.ts, apps/web/src/hooks/use-scroll-restoration.ts, apps/web/src/pages/_app.tsx
=> Временный фикс позиции скролла при нажатии «Назад» в браузере

apps/api/src/modules/comments/procedures/vote.ts, apps/api/src/modules/posts/procedures/vote.ts, apps/web/src/components/comments/comment-vote/comment-vote.view.tsx, apps/web/src/components/posts/post-vote/post-vote.view.tsx, packages/prisma-client/prisma/migrations/20221002123140_rm_votes_of_own_posts_comments/migration.sql
=> Добавил запрет на оценку своих постов/комментариев

apps/api/src/modules/comments/inputs/index.ts, apps/api/src/modules/comments/inputs/update-comment.input.ts, apps/api/src/modules/comments/procedures/index.ts, apps/api/src/modules/comments/procedures/update.ts, apps/api/src/modules/comments/router.ts, apps/web/src/components/comments/post-comments/comment/comment.tsx, apps/web/src/components/comments/post-comments/edit-comment-form/edit-comment-form.state.ts, apps/web/src/components/comments/post-comments/edit-comment-form/edit-comment-form.view.tsx, apps/web/src/components/comments/post-comments/edit-comment-form/index.ts, apps/web/src/components/comments/post-comments/new-comment-form/index.ts, apps/web/src/components/comments/post-comments/post-comments.view.tsx
=> Добавил редактирование комментариев

apps/web/src/components/comments/post-comments/comment/comment.tsx, apps/web/src/pages/posts/[id]/index.tsx
=> Добавил обновление поста и ленты комментариев при создании комментария

apps/api/src/modules/posts/procedures/get-one.ts
=> Убрал доступ по прямой ссылке для распубликованных постов

apps/web/src/components/embed/embed.tsx, apps/web/src/pages/top/[interval].tsx, apps/web/src/pages/users/[id].tsx
=> Добавил комментарии пользователя на его страницу

apps/api/src/modules/comments/procedures/create.ts, apps/api/src/modules/index.ts, apps/api/src/modules/notifications/index.ts, apps/api/src/modules/notifications/inputs/get.ts, apps/api/src/modules/notifications/inputs/index.ts, apps/api/src/modules/notifications/inputs/read.ts, apps/api/src/modules/notifications/procedures/get-unread-count.ts, apps/api/src/modules/notifications/procedures/get.ts, apps/api/src/modules/notifications/procedures/index.ts, apps/api/src/modules/notifications/procedures/read.ts, apps/api/src/modules/notifications/router.ts, apps/api/src/router.ts, apps/api/src/utilities/pagination.ts, apps/web/src/components/navbar/right-side.tsx, apps/web/src/components/navbar/user.tsx, apps/web/src/components/notifications/index.ts, apps/web/src/components/notifications/notification-list/index.ts, apps/web/src/components/notifications/notification-list/notification-list.tsx, apps/web/src/components/notifications/notification/index.ts, apps/web/src/components/notifications/notification/notification.tsx, apps/web/src/components/notifications/notifications-button/index.ts, apps/web/src/components/notifications/notifications-button/notifications-button.tsx, apps/web/src/hooks/use-infinite-scroll.ts, packages/prisma-client/prisma/migrations/20221016092646_add_notification_model/migration.sql, packages/prisma-client/prisma/migrations/20221016120822_add_comment_notification_model/migration.sql, packages/prisma-client/prisma/migrations/20221016121201_add_comment_to_comment_notification/migration.sql, packages/prisma-client/prisma/schema.prisma
=> Добавил уведомления о новых комментариях к посту
